const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Windows-only build fix: point CMake at a ninja new enough to handle long paths.
 *
 * Why this is needed
 * ------------------
 * CMake mirrors each source file's ABSOLUTE path inside the object directory, so
 * a Fabric codegen object for react-native-keyboard-controller lands at:
 *
 *   <project>/android/app/.cxx/Debug/<hash>/arm64-v8a
 *     /reactnativekeyboardcontroller_autolinked_build/CMakeFiles
 *     /react_codegen_reactnativekeyboardcontroller.dir
 *     /C_/<project-without-drive>/node_modules/react-native-keyboard-controller
 *     /common/cpp/react/renderer/components/reactnativekeyboardcontroller
 *     /RNKCKeyboardBackgroundViewShadowNode.cpp.o
 *
 * ...which is 425 characters. ninja 1.10 (the build bundled with Android SDK
 * cmake 3.22.1) refuses to stat anything past 260 and fails the build.
 *
 * Fixes that do NOT work, so nobody has to retry them:
 *   - Enabling LongPathsEnabled in the registry. It is already 1 on this machine;
 *     ninja 1.10 does not use the \\?\ prefix, so the OS opt-in never applies.
 *   - Moving the project to a short path such as C:\dev\svk. The invariant part of
 *     that path — the codegen middle plus the filename, with no project prefix at
 *     all — is 290 characters on its own, so even a zero-length root still fails.
 *   - -DCMAKE_OBJECT_PATH_MAX. CMake accepts it (it lands in CMakeCache) but only
 *     the Makefile generators act on it; the Ninja generator ignores it.
 *
 * What works is a newer ninja, which does use the long-path APIs.
 *
 * Getting one (once per machine):
 *   pip install ninja          # ships upstream binaries, currently 1.13
 * then either let this plugin find it on PATH, or set NINJA_PATH to it, or drop
 * the binary at <project>/.tools/ninja.exe.
 *
 * This is a no-op on macOS, Linux and EAS Build, none of which has the limit.
 */

const MARKER = '// @generated by plugins/withWindowsNinja.js';
const MIN_MAJOR = 1;
const MIN_MINOR = 11;

/** Returns the ninja version as [major, minor], or null if it won't run. */
function versionOf(binary) {
  try {
    const out = execFileSync(binary, ['--version'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    const m = out.match(/^(\d+)\.(\d+)/);
    return m ? [Number(m[1]), Number(m[2])] : null;
  } catch {
    return null;
  }
}

function isNewEnough(binary) {
  const v = versionOf(binary);
  if (!v) return false;
  const [major, minor] = v;
  return major > MIN_MAJOR || (major === MIN_MAJOR && minor >= MIN_MINOR);
}

/** First ninja that can handle long paths: env var, then repo-local, then PATH. */
function resolveNinja(projectRoot) {
  const candidates = [];
  if (process.env.NINJA_PATH) candidates.push(process.env.NINJA_PATH);
  candidates.push(path.join(projectRoot, '.tools', 'ninja.exe'));

  try {
    const fromPath = execFileSync('where', ['ninja'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    candidates.push(...fromPath);
  } catch {
    // `where` exits non-zero when nothing matches — nothing to add.
  }

  for (const candidate of candidates) {
    // A bare name from PATH has no file to stat; let execFileSync decide.
    const exists = path.isAbsolute(candidate) ? fs.existsSync(candidate) : true;
    if (exists && isNewEnough(candidate)) return candidate;
  }
  return null;
}

const withWindowsNinja = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (process.platform !== 'win32') return cfg;

    // Groovy strings and CMake both want forward slashes.
    const projectRoot = cfg.modRequest.projectRoot;
    const ninja = resolveNinja(projectRoot);

    if (!ninja) {
      console.warn(
        '[withWindowsNinja] No ninja >= 1.11 found, so the Android C++ build will\n' +
          '  likely fail with "Filename longer than 260 characters".\n' +
          '  Run `pip install ninja`, or set NINJA_PATH, or place the binary at\n' +
          '  .tools/ninja.exe. See plugins/withWindowsNinja.js for the details.',
      );
      return cfg;
    }

    if (cfg.modResults.contents.includes(MARKER)) return cfg;

    const injected = [
      '',
      `        ${MARKER}`,
      '        // Long Fabric-codegen object paths exceed the 260-char limit that the',
      "        // Android SDK's bundled ninja 1.10 enforces. A newer ninja handles them.",
      '        externalNativeBuild {',
      '            cmake {',
      `                arguments "-DCMAKE_MAKE_PROGRAM=${ninja.replace(/\\/g, '/')}"`,
      '            }',
      '        }',
    ].join('\n');

    const anchor = /(\n[ \t]*defaultConfig[ \t]*\{)/;
    if (!anchor.test(cfg.modResults.contents)) {
      throw new Error(
        '[withWindowsNinja] Could not find the `defaultConfig {` block in ' +
          'android/app/build.gradle, so the ninja override was not applied.',
      );
    }
    cfg.modResults.contents = cfg.modResults.contents.replace(anchor, `$1${injected}`);
    return cfg;
  });

module.exports = withWindowsNinja;
